name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    


    steps:
    
    - uses: egor-tensin/setup-mingw@v2
      with:
           platform: x64
    - uses: actions/checkout@v3
    - name: make
      run: gcc -DUNICODE -w main.c IComponent.cpp Canvas.cpp -lgdi32
